FROM node:18-alpine

# Install dependencies only when needed
RUN apk add --no-cache libc6-compat

WORKDIR /app

# Install dependencies based on the preferred package manager
COPY package.json package-lock.json* ./
RUN npm ci

# Copy application code
COPY . .

# Next.js collects completely anonymous telemetry data about general usage.
# Learn more here: https://nextjs.org/telemetry
# Uncomment the following line in case you want to disable telemetry during development.
ENV NEXT_TELEMETRY_DISABLED 1

# Expose port
EXPOSE 3000

ENV PORT 3000
ENV NODE_ENV development

CMD ["npm", "run", "dev"]